/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'benediktvb15' at '10/23/16 12:57 PM' with Gradle 3.1
 *
 * @author benediktvb15, @date 10/23/16 12:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
